config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :blog_posts
end

app/models/blog_post.rb
#:model
class BlogPost < ActiveRecord::Base
end
#:model end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/models/user.rb
#:model
class User < ActiveRecord::Base
  has_many :blog_post
end
#:model end

app/controllers/application_controller.rb
require 'action_controller'

#:appcontroller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #:render

  #:render end
  # def render(cell_constant, model, options: {})
  #   super(
  #         html: cell(
  #               cell_constant,
  #               model,
  #               { layout: Home::Cell::Layout,
  #                 # context: { current_user: current_user, flash: flash }
  #                 context: { flash: flash }
  #                 }.merge(options))
  #         )
  # end

#:run_options
private
  # def _run_options(options)
  #   options.merge("current_user" => tyrant.current_user )
  # end
#:run_options end
end
#:appcontroller end

app/controllers/blog_posts_controller.rb
#:new
# app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  #~doc
  # The #run method comes from trailblazer-rails.
  # https://trailblazer.to/2.1/docs/trailblazer.html#trailblazer-rails-run
  #
  # It runs the given operation and automatically passes `{params: params}`
  # into the operation invocation, as so
  #
  #    def new
  #      ctx = BlogPost::Operation::Create::Present.call(params: params)
  #
  # You can configure additional default variables going into the operation
  # by overriding {Controller#_run_options}:
  # https://trailblazer.to/2.1/docs/trailblazer.html#trailblazer-rails-run-controller-runtime-variables
  #
  # An alternative approach is to use endpoints - we will do this in a later chapter.
  #~doc end
  def new
    run BlogPost::Operation::Create::Present do |ctx|

      @form = ctx["contract.default"]
      render
    end
  end
#:new end

  #:create
  # app/controllers/blog_posts_controller.rb
  def create
    _ctx = run BlogPost::Operation::Create do |ctx|
      return redirect_to blog_posts_path
    end

    @form = _ctx["contract.default"]
    render :new
  end
  #:create end

  #:show
  # app/controllers/blog_posts_controller.rb
  def show
    run BlogPost::Operation::Show do |ctx|
      @model = ctx[:model]
      render
    end
  end
  #:show end

  #:index
  # app/controllers/blog_posts_controller.rb
  def index
    run BlogPost::Operation::Index do |ctx|
      @model = ctx[:model]
      @total = @model.count

      render
    end

  end
  #:index end

  #:edit
  # app/controllers/blog_posts_controller.rb
  def edit
    run BlogPost::Operation::Update::Present do |ctx|
      @form   = ctx["contract.default"]
      @title  = "Editing #{ctx[:model].title}"

      render
    end

  end
  #:edit end

  #:update
  # app/controllers/blog_posts_controller.rb
  def update
    _ctx = run BlogPost::Operation::Update do |ctx|
      flash[:notice] = "#{ctx[:model].title} has been saved"
      return redirect_to blog_post_path(ctx[:model].id)
    end

    @form   = _ctx["contract.default"] # FIXME: redundant to #create!
    @title  = "Editing #{_ctx[:model].title}"

    render :edit
  end
  #:update end

  #:delete
  # app/controllers/blog_posts_controller.rb
  def destroy
    run BlogPost::Operation::Delete

    flash[:notice] = "Post deleted"
    redirect_to blog_posts_path
  end
  #:delete end
end

app/views/blog_posts/edit.html.erb
#:edit
# app/views/blog_posts/edit.html.erb
<h1>Editing "<%= @model.title %>"</h1>

<%= simple_form_for @form, as: :blog_post, url: blog_post_path(@model.id), method: :patch do |f| %>
  <div class="row">
      <%= f.input :title, placeholder: "Title", label: false %>
  </div>
  <div class="row">
      <%= f.input :body, placeholder: "Say it out loud!", label: false %>
  </div>
  <div class="row">
      <%= f.submit "Create Post" %>
  </div>
<% end %>
#:edit end

app/views/blog_posts/index.html.erb
#:index
# app/views/blog_posts/index.html.erb
<div class="header">
  Total: <%= @total %>
</div>

<%= @model.each do |blog_post| %>
  <h2>
    <%= blog_post.title %>
  </h2>

  <div class="created_at">
    Posted at <%= blog_post.created_at %>
  </div>

  <div class="body">
    <%= blog_post.body %>

  </div>
  <p>
   <%= link_to "Edit", edit_blog_post_path(blog_post.id) %>
  </p>
  <p>
   <%= button_to "Delete", blog_post_path(blog_post.id), method: :delete %>
  </p>

  <hr>
<% end %>
#:index end

app/views/blog_posts/new.html.erb
#:new
<!-- app/views/blog_posts/new.html.erb -->
<h1>New Post</h1>

<%= simple_form_for @form, as: :blog_post, url: blog_posts_path do |f| %>
  <div class="row">
      <%= f.input :title, placeholder: "Title", label: false %>
  </div>
  <div class="row">
      <%= f.input :body, placeholder: "Say it out loud!", label: false %>
  </div>
  <div class="row">
      <%= f.submit "Create Post" %>
  </div>
<% end %>
#:new end

app/views/blog_posts/show.html.erb
<h2>
  <%= @model.title %>
</h2>

<div class="created_at">
  Posted at <%= @model.created_at %>
</div>

<div class="body">
  <%= @model.body %>

</div>
<p>
 <%= link_to "Edit", edit_blog_post_path(@model.id) %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hello!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="flash">
      <%= flash[:notice] %>
    </div>

    <div class="name">
      <ul>
        <li><%= link_to "New", new_blog_post_path %></li>
      </ul>
    </div>

    <hr>

    <%= yield %>
  </body>
</html>